PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (count (?ee) as ?count)
WHERE {
  ?publication rdfs:seeAlso ?ee
}
# cannot both order an count as the counted variable is not projected
# ORDER BY ?ee
LIMIT 10
OFFSET 50
