# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Addition
# A + B in FILTER expressions
# /Users/ben/repos/datagraph/tests/tests/data-r2/expr-ops/query-plus-1.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#plus-1
#
#
# 
# This test is approved: http://lists.w3.org/Archives/Public/public-rdf-dawg/2007JulSep/att-0087/14-dawg-minutes.html
#
describe "W3C test " do
  context "expr-ops" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .
@prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .

:x1 :p "1"^^xsd:integer .
:x2 :p "2"^^xsd:integer .
:x3 :p "3"^^xsd:integer .
:x4 :p "4"^^xsd:integer .

}
      @query = %q{
PREFIX : <http://example.org/>
SELECT ?s WHERE {
    ?s :p ?o .
    ?s2 :p ?o2 .
    FILTER(?o + ?o2 = 3) .
}

}
    end

    it "Addition" do
    
      graphs = { :default => { :data => @data, :format => :ttl} }

      repository = 'expr-ops-plus-1'
      results = [
          { 
              "s" => RDF::URI('http://example.org/x1'),
          },
          { 
              "s" => RDF::URI('http://example.org/x2'),
          },
      ]


      
      sparql_query(:graphs => graphs, :query => @query, 
                   :repository => repository, :form => :select)
    end
  end
end
