# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Calculate which sets are subsets of others (exclude A subsetOf A)
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/negation/subset-02.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#subset-02
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "negation" do
    before :all do
      @data = %q{
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix :        <http://example/> .

:a rdf:type :Set .
:a :member 1 .
:a :member 2 .
:a :member 3 .

:b rdf:type :Set .
:b :member 1 .
:b :member 9 .

:c rdf:type :Set .
:c :member 1 .
:c :member 2 . 

:d rdf:type :Set .
:d :member 1 .
:d :member 9 .

:e rdf:type :Set .
:e :member 1 .
:e :member 2 . 

:empty rdf:type :Set .

}
      @query = %q{
PREFIX :    <http://example/>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (?s1 AS ?subset) (?s2 AS ?superset)
WHERE
{
    # All pairs of sets
    ?s2 rdf:type :Set .
    ?s1 rdf:type :Set .

    MINUS {
        ?s1 rdf:type :Set .
        ?s2 rdf:type :Set .
        # Assumes ?s1 has at least one member 
        ?s1 :member ?x .
        # If we want to exclude A as a subset of A.
        # This is not perfect as "?s1 = ?s2" is not a
        # contents based comparison.
        FILTER ( ?s1 = ?s2 || NOT EXISTS { ?s2 :member ?x . } )
    }
    MINUS {
        # If we don't want the empty set being a subset of itself.
        ?s1 rdf:type :Set .
        ?s2 rdf:type :Set .
        # Choose the pair (empty set, empty set)
        FILTER ( NOT EXISTS { ?s1 :member ?y . } )
        FILTER ( NOT EXISTS { ?s2 :member ?y . } )
    }
}

}
    end

    example "Calculate which sets are subsets of others (exclude A subsetOf A)", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'negation-subset-02'
      expected = [
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/e'),
          },
          { 
              :subset => RDF::URI('http://example/c'),
              :superset => RDF::URI('http://example/e'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/d'),
          },
          { 
              :subset => RDF::URI('http://example/b'),
              :superset => RDF::URI('http://example/d'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/c'),
          },
          { 
              :subset => RDF::URI('http://example/e'),
              :superset => RDF::URI('http://example/c'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/b'),
          },
          { 
              :subset => RDF::URI('http://example/d'),
              :superset => RDF::URI('http://example/b'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/a'),
          },
          { 
              :subset => RDF::URI('http://example/e'),
              :superset => RDF::URI('http://example/a'),
          },
          { 
              :subset => RDF::URI('http://example/c'),
              :superset => RDF::URI('http://example/a'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
