# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Subsets by exclusion (MINUS)
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/negation/subsetByExcl02.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#subset-by-exclusion-minus-1
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "negation" do
    before :all do
      @data = %q{
@prefix ex: <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/negation#> .

ex:lifeForm1 a ex:Mammal, ex:Animal .
ex:lifeForm2 a ex:Reptile, ex:Animal .
ex:lifeForm3 a ex:Insect, ex:Animal .
}
      @query = %q{
PREFIX ex: <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/negation#>
SELECT ?animal { 
  ?animal a ex:Animal MINUS { 
    ?animal a ?type 
    FILTER(?type = ex:Reptile || ?type = ex:Insect) 
  } 
}
}
    end

    example "Subsets by exclusion (MINUS)", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'negation-subset-by-exclusion-minus-1'
      expected = [
          { 
              :animal => RDF::URI('http://www.w3.org/2009/sparql/docs/tests/data-sparql11/negation#lifeForm1'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
