# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Calculate which sets are subsets of others (include A subsetOf A)
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/negation/subset-01.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#subset-01
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "negation" do
    before :all do
      @data = %q{
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix :        <http://example/> .

:a rdf:type :Set .
:a :member 1 .
:a :member 2 .
:a :member 3 .

:b rdf:type :Set .
:b :member 1 .
:b :member 9 .

:c rdf:type :Set .
:c :member 1 .
:c :member 2 . 

:d rdf:type :Set .
:d :member 1 .
:d :member 9 .

:e rdf:type :Set .
:e :member 1 .
:e :member 2 . 

:empty rdf:type :Set .

}
      @query = %q{
PREFIX :    <http://example/>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# SPARQL 1.1
SELECT (?s1 AS ?subset) (?s2 AS ?superset)
WHERE
{
    # All pairs of sets except (S,S)
    ?s2 rdf:type :Set .
    ?s1 rdf:type :Set .
    FILTER(?s1 != ?s2)
    MINUS 
    {
    	# The MINUS RHS is (?s1, ?s2) where 
        # ?s1 has a member not in ?s2
        ?s1 rdf:type :Set .
        ?s2 rdf:type :Set .
        FILTER(?s1 != ?s2)

        ?s1 :member ?x .
        FILTER NOT EXISTS { ?s2 :member ?x . }
    }
}

}
    end

    example "Calculate which sets are subsets of others (include A subsetOf A)", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'negation-subset-01'
      expected = [
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/e'),
          },
          { 
              :subset => RDF::URI('http://example/c'),
              :superset => RDF::URI('http://example/e'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/d'),
          },
          { 
              :subset => RDF::URI('http://example/b'),
              :superset => RDF::URI('http://example/d'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/c'),
          },
          { 
              :subset => RDF::URI('http://example/e'),
              :superset => RDF::URI('http://example/c'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/b'),
          },
          { 
              :subset => RDF::URI('http://example/d'),
              :superset => RDF::URI('http://example/b'),
          },
          { 
              :subset => RDF::URI('http://example/empty'),
              :superset => RDF::URI('http://example/a'),
          },
          { 
              :subset => RDF::URI('http://example/e'),
              :superset => RDF::URI('http://example/a'),
          },
          { 
              :subset => RDF::URI('http://example/c'),
              :superset => RDF::URI('http://example/a'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
