# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# INSERT 03
# This is a INSERT over a dataset with a single triple in a named graph, inserting into the named graph using the WITH keyword
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/basic-update/insert-03.ru
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#insert-where-03
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "basic-update" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .

:a :b :c .

}
       # http://example.org/g1
       @graph0 = %q{
<http://example.org/s> <http://example.org/p> "o" .

}
      @query = %q{
PREFIX     : <http://example.org/> 

WITH :g1
INSERT {
	?s ?p "z"
} WHERE {
	?s ?p ?o
}

}
    end

    example "INSERT 03", :status => 'unverified', :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}

      graphs[RDF::URI('http://example.org/g1')] = { :data => @graph0, :format => :ttl }

      repository = 'basic-update-insert-where-03'
      expected = [
          { 
            :s => RDF::URI('http://example.org/a'),
            :p => RDF::URI('http://example.org/b'),
            :o => RDF::URI('http://example.org/c'),
            :g => nil
          },
          { 
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('o' ),
            :g => RDF::URI('http://example.org/g1')
          },
          { 
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('z' ),
            :g => RDF::URI('http://example.org/g1')
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :update).should =~ expected
    end
  end
end
