# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# INSERT 01
# This is a INSERT over a dataset with a single triple in the default graph
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/basic-update/insert-01.ru
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#insert-where-01
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "basic-update" do
    before :all do
      @data = %q{
<http://example.org/s> <http://example.org/p> "o" .

}
      @query = %q{
PREFIX     : <http://example.org/> 

INSERT {
	?s ?p "q"
} WHERE {
	?s ?p ?o
}

}
    end

    example "INSERT 01", :status => 'unverified', :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'basic-update-insert-where-01'
      expected = [
          {
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('o' ),
            :g => nil
          },
          {
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('q' ),
            :g => nil
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :update).should =~ expected
    end
  end
end
