# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# INSERT 04
# This is a INSERT of a triple over a dataset with data in named graphs, inserting into the default graph using the USING keyword
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/basic-update/insert-04.ru
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#insert-where-04
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "basic-update" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .

:a :b :c .

}
       # http://example.org/g1
       @graph0 = %q{
@prefix : <http://example.org/> .

:s :p "o" .

}
      @query = %q{
PREFIX     : <http://example.org/> 

INSERT {
	?s ?p "q"
}
USING :g1
WHERE {
	?s ?p ?o
}

}
    end

    example "INSERT 04", :status => 'unverified', :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}

      graphs[RDF::URI('http://example.org/g1')] = { :data => @graph0, :format => :ttl }

      repository = 'basic-update-insert-where-04'
      expected = [
          { 
            :s => RDF::URI('http://example.org/a'),
            :p => RDF::URI('http://example.org/b'),
            :o => RDF::URI('http://example.org/c'),
            
          { 
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('q' ),
            
          { 
            :s => RDF::URI('http://example.org/s'),
            :p => RDF::URI('http://example.org/p'),
            :o => RDF::Literal.new('o' ),
            
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :update).should =~ expected
    end
  end
end
