# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Zero Length Paths with Literals
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/property-path/pp13.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#pp13
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "property-path" do
    before :all do
      @data = %q{
@prefix : <http://ex.org/> .

:s :p "o".

}
      @query = %q{
prefix : <http://ex.org/>

select * 
WHERE{ ?X :p{0} ?Y  }
ORDER BY ?X

}
    end

    example "Zero Length Paths with Literals", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'property-path-pp13'
      expected = [
          { 
              :X => RDF::URI('http://ex.org/s'),
              :Y => RDF::URI('http://ex.org/s'),
          },
          { 
              :X => RDF::Literal.new('o' ),
              :Y => RDF::Literal.new('o' ),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
