# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Diamond -- :p{2}
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/property-path/path-2-1.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#pp20
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "property-path" do
    before :all do
      @data = %q{
@prefix : <http://example/> .

:a :p :b .
:b :p :z .
:a :p :c .
:c :p :z .

}
      @query = %q{
prefix : <http://example/> 

select * where {
    :a :p{2} ?z
} 

}
    end

    example "Diamond -- :p{2}", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'property-path-pp20'
      expected = [
          { 
              :z => RDF::URI('http://example/z'),
          },
          { 
              :z => RDF::URI('http://example/z'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
