# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# (pp33) Operator precedence 4
# 
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/property-path/path-p4.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#pp33
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2011-03-29#resolution_3
#
describe "W3C test" do
  context "property-path" do
    before :all do
      @data = %q{
@prefix :  <http://www.example.org/> .

:a :p0 :c .
:a :p3 :b .
:d :p1 :a .
:d :p2 :e .
:c :p2 :f .
:c :p3 :g .



}
      @query = %q{
prefix :  <http://www.example.org/>
select ?t
where {
  :a (:p0|^:p1)/:p2|:p3 ?t
}
}
    end

    example "(pp33) Operator precedence 4", :status => 'unverified' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'property-path-pp33'
      expected = [
          { 
              :t => RDF::URI('http://www.example.org/e'),
          },
          { 
              :t => RDF::URI('http://www.example.org/f'),
          },
          { 
              :t => RDF::URI('http://www.example.org/b'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
