# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# (pp34) Named Graph 1
# 
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/property-path/path-ng-01.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#pp34
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2011-04-05#resolution_2
#
describe "W3C test" do
  context "property-path" do
    before :all do
       # ng-01.ttl
       @graph0 = %q{
@prefix :  <http://www.example.org/> .

:a :p1 :b .

}
       # ng-02.ttl
       @graph1 = %q{
@prefix :  <http://www.example.org/> .

:a :p1 :c .
}
       # ng-03.ttl
       @graph2 = %q{
@prefix :  <http://www.example.org/> .

:a :p1 :d .
}
      @query = %q{
prefix :  <http://www.example.org/>
select ?t
where {
  GRAPH <http://example.org/ng-01.ttl> {
    ?s :p1* ?t }
}
}
    end

    example "(pp34) Named Graph 1", :status => 'unverified' do
    
      graphs = {}
      graphs[:default] = nil

      graphs[RDF::URI('http://example.org/ng-01.ttl')] = { :data => @graph0, :format => :ttl }
      graphs[RDF::URI('http://example.org/ng-02.ttl')] = { :data => @graph1, :format => :ttl }
      graphs[RDF::URI('http://example.org/ng-03.ttl')] = { :data => @graph2, :format => :ttl }

      repository = 'property-path-pp34'
      expected = [
          { 
              :t => RDF::URI('http://www.example.org/a'),
          },
          { 
              :t => RDF::URI('http://www.example.org/b'),
          },
          { 
              :t => RDF::URI('http://www.example.org/b'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
