# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# bind03 - BIND
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/bind/bind03.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#bind03
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "bind" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .

:s1 :p 1 .
:s2 :p 2 .
:s3 :p 3 .
:s4 :p 4 .

}
      @query = %q{
PREFIX : <http://example.org/> 

SELECT ?z ?s1
{
  ?s ?p ?o .
  BIND(?o+1 AS ?z)
  ?s1 ?p1 ?z
}

}
    end

    example "bind03 - BIND", :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'bind-bind03'
      expected = [
          { 
              :s1 => RDF::URI('http://example.org/s4'),
              :z => RDF::Literal.new('4' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
          },
          { 
              :s1 => RDF::URI('http://example.org/s3'),
              :z => RDF::Literal.new('3' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
          },
          { 
              :s1 => RDF::URI('http://example.org/s2'),
              :z => RDF::Literal.new('2' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
