# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# graph-05
# Data: default and named / Query: default graph
# /Users/ben/repos/datagraph/tests/tests/data-r2/graph/graph-05.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#dawg-graph-05
#
#
# 
# This test is approved: http://lists.w3.org/Archives/Public/public-rdf-dawg/2007JulSep/att-0047/31-dawg-minutes
#
describe "W3C test " do
  context "graph" do
    before :all do
      @data = %q{
@prefix : <http://example/> .
@prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .

:x :p "1"^^xsd:integer .
:a :p "9"^^xsd:integer .

}
      @query = %q{
PREFIX : <http://example/> 

SELECT * { ?s ?p ?o }

}
    end

    it "graph-05" do
    
      graphs = { :default => { :data => @data, :format => :ttl} }

      repository = 'graph-dawg-graph-05'
      results = [
          { 
              "s" => RDF::URI('http://example/x'),
              "o" => RDF::Literal.new('1' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
              "p" => RDF::URI('http://example/p'),
          },
          { 
              "o" => RDF::Literal.new('9' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
              "s" => RDF::URI('http://example/a'),
              "p" => RDF::URI('http://example/p'),
          },
      ]


      
      sparql_query(:graphs => graphs, :query => @query, 
                   :repository => repository, :form => :select)
    end
  end
end
