# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# constructwhere04 - CONSTRUCT WHERE
# CONSTRUCT WHERE  with DatasetClause
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/construct/constructwhere04.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#constructwhere04
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2011-02-01#resolution_3
#
describe "W3C test" do
  context "construct" do
    before :all do
      @graph = %q{
@prefix : <http://example.org/> .

:s1 :p :o1 .
:s2 :p :o1 .
:s2 :p :o2 .
:s3 :p :o3 .

}
      @query = %q{
PREFIX : <http://example.org/>

CONSTRUCT 
FROM <data.ttl>
WHERE { ?s ?p ?o }
}
    end

    example "constructwhere04 - CONSTRUCT WHERE" do
    
      graphs = {}
      graphs[:default] = nil
      graphs[RDF::URI('data.ttl')] = { :data => @graph, :format => :ttl }

      repository = 'construct-constructwhere04'
      expected = RDF::Graph.new do | graph |
        graph << RDF::Statement.new(
            :subject => RDF::URI('http://example.org/s2'),
            :predicate => RDF::URI('http://example.org/p'),
            :object => RDF::URI('http://example.org/o1'))
        graph << RDF::Statement.new(
            :subject => RDF::URI('http://example.org/s2'),
            :predicate => RDF::URI('http://example.org/p'),
            :object => RDF::URI('http://example.org/o2'))
        graph << RDF::Statement.new(
            :subject => RDF::URI('http://example.org/s1'),
            :predicate => RDF::URI('http://example.org/p'),
            :object => RDF::URI('http://example.org/o1'))
        graph << RDF::Statement.new(
            :subject => RDF::URI('http://example.org/s3'),
            :predicate => RDF::URI('http://example.org/p'),
            :object => RDF::URI('http://example.org/o3'))
      end
      sparql_query(:graphs => graphs, :query => @query,
                   :repository => repository, :form => :construct).should be_isomorphic_with expected
    end
  end
end
