# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# constructwhere06
# 
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2009/sparql/docs/tests/data-sparql11/construct
#
describe "W3C test" do
  context "construct" do
    before :all do
      @query = IO.read(File.dirname(__FILE__) + "/constructwhere06.rq");
      @data = "" 
    end

    example "constructwhere06 - CONSTRUCT WHERE negative syntax", :w3c_status => 'approved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}

      repository = 'construct-constructwhere06'

      expect { sparql_query(:graphs => graphs, :query => @query,
                            :repository => repository, :form => :construct) }.to raise_error
    end
  end
end
