# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# constructwhere04 - CONSTRUCT WHERE
# CONSTRUCT WHERE  with DatasetClause
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/construct/constructwhere04.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#constructwhere04
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2011-02-01#resolution_3
#
describe "W3C test" do
  context "construct" do
    before :all do
      @query = %q{
PREFIX : <http://example.org/>

CONSTRUCT 
FROM <data.ttl>
WHERE { ?s ?p ?o }
}
    end

    example "constructwhere04 - CONSTRUCT WHERE", :status => 'unverified' do
    
      graphs = {}
      graphs[:default] = nil


      repository = 'construct-constructwhere04'


        raise NotImplementedError("This test form is not yet implemented")
    end
  end
end
