# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# constructwhere03 - CONSTRUCT WHERE
# CONSTRUCT WHERE  with join, using shortcut notation
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/construct/constructwhere03.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#constructwhere03
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2011-02-01#resolution_3
#
describe "W3C test" do
  context "construct" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .

:s1 :p :o1 .
:s2 :p :o1 .
:s2 :p :o2 .
:s3 :p :o3 .

}
      @query = %q{
PREFIX : <http://example.org/>

CONSTRUCT WHERE { :s2 :p ?o1, ?o2 }
}
    end

    example "constructwhere03 - CONSTRUCT WHERE", :status => 'unverified' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'construct-constructwhere03'


        raise NotImplementedError("This test form is not yet implemented")
    end
  end
end
