# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Nodes: Distinct
# 
# /Users/ben/repos/datagraph/tests/tests/data-r2/distinct/distinct-1.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#distinct-3
#
#
# 
# This test is approved: http://www.w3.org/2007/07/17-dawg-minutes
#
describe "W3C test " do
  context "distinct" do
    before :all do
      @data = %q{
@prefix :         <http://example/> .
@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .

:x1 :p1 :z1 .
:x1 :p1 _:a .

:x1 :p2 :z1 .
:x1 :p2 _:a .


}
      @query = %q{
(select (?v)
        (distinct
         (project (?v)
                  (bgp (triple ?x ?p ?v)))))

}
    end

    it "Nodes: Distinct" do
    
      graphs = { :default => { :data => @data, :format => :ttl} }

      repository = 'distinct-distinct-3'
      results = [
          { 
              "v" => RDF::Node.new('b0'),
          },
          { 
              "v" => RDF::URI('http://example/z1'),
          },
      ]


      
      sparql_query(:graphs => graphs, :query => @query, 
                   :repository => repository, :form => :select)
    end
  end
end
