# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# OWL DS bnodes are not existentials
# 
# /Users/ben/Repos/dydra/tests/tests/sparql11-tests/data-sparql11/entailment/owlds01.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#owlds01
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "entailment" do
    before :all do
      @data = %q{
@prefix :  <http://example.org/x/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

_:ont a owl:Ontology .

:p rdf:type owl:ObjectProperty .

:a rdf:type :c .
:a rdf:type :d .
:a rdf:type _:x .

_:x rdf:type owl:Restriction.
_:x owl:onProperty :p.
_:x owl:someValuesFrom :c .

}
      @query = %q{
PREFIX   ex:  <http://example.org/x/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?x ?c
WHERE { 
?x rdf:type ?c . 
?c rdfs:subClassOf ex:c . 
?x ex:p _:y . 

}

}
    end

    example "OWL DS bnodes are not existentials", :status => 'unverified', :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'entailment-owlds01'
      expected = [
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
