# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# RDF inference test for rdf:_n occuring in the data
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/entailment/rdf02.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#rdf02
#
# This test is approved: 
# 
#
describe "W3C test" do
  context "entailment" do
    before :all do
      @data = %q{
@prefix ex: <http://example.org/ns#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ex:favourite-fruit a rdf:Seq .
ex:favourite-fruit rdf:_1 ex:banana .
ex:favourite-fruit rdf:_2 ex:apple .
ex:favourite-fruit rdf:_3 ex:pear .

}
      @query = %q{
PREFIX ex: <http://example.org/ns#>
SELECT ?x
WHERE {
  ?x rdf:type rdf:Property .
}


}
    end

    example "RDF inference test for rdf:_n occuring in the data", :unverified => true, :w3c_status => 'unapproved' do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'entailment-rdf02'
      expected = [
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#subject'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#object'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#first'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#rest'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#value'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#_1'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#_2'),
          },
          { 
              :x => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#_3'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
