# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# dawg-construct-identity
# Graph equivalent result graph
# /Users/ben/repos/datagraph/tests/tests/data-r2/construct/query-ident.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#construct-1
#
# This test is approved: 
# http://lists.w3.org/Archives/Public/public-rdf-dawg/2007JulSep/att-0047/31-dawg-minutes
#
# 20101219 jaa : bug indicator : construct not yet supported by the front-end
# 20110203 jaa : ++ support for construct

describe "W3C test" do
  context "construct" do
    before :all do
      @data = %q{
@prefix foaf:       <http://xmlns.com/foaf/0.1/> .
@prefix rdf:        <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:	    <http://www.w3.org/2000/01/rdf-schema#> .

_:alice
    rdf:type        foaf:Person ;
    foaf:name       "Alice" ;
    foaf:mbox       <mailto:alice@work> ;
    foaf:knows      _:bob ;
    .

_:bob
    rdf:type        foaf:Person ;
    foaf:name       "Bob" ; 
    foaf:knows      _:alice ;
    foaf:mbox       <mailto:bob@work> ;
    foaf:mbox       <mailto:bob@home> ;
    .

}
      @query = %q{
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX  foaf:       <http://xmlns.com/foaf/0.1/>

CONSTRUCT { ?s ?p ?o . }
WHERE {
  ?s ?p ?o .
}

}
    end

    example "dawg-construct-identity" do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'construct-construct-1'

      expected = RDF::Graph.new do | graph |
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('alice'),
            :predicate => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
            :object => RDF::URI('http://xmlns.com/foaf/0.1/Person'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('alice'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/name'),
            :object => RDF::Literal('Alice'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('alice'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/mbox'),
            :object => RDF::URI('mailto:alice@work'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('alice'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/knows'),
            :object => RDF::Node.new('bob'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('bob'),
            :predicate => RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
            :object => RDF::URI('http://xmlns.com/foaf/0.1/Person'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('bob'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/name'),
            :object => RDF::Literal('Bob'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('bob'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/knows'),
            :object => RDF::Node.new('alice'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('bob'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/mbox'),
            :object => RDF::URI('mailto:bob@work'))
        graph << RDF::Statement.new(
            :subject => RDF::Node.new('bob'),
            :predicate => RDF::URI('http://xmlns.com/foaf/0.1/mbox'),
            :object => RDF::URI('mailto:bob@home'))
      end
      sparql_query(:graphs => graphs, :query => @query,
                   :repository => repository, :form => :construct).should be_isomorphic_with expected

    end
  end
end
