# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Expression may return no value
# 
# /Users/ben/Repos/datagraph/tests/tests/sparql11-tests/data-sparql11/project-expression/projexp05.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#projexp05
#
# This test is approved: 
# http://www.w3.org/2009/sparql/meeting/2010-09-07#resolution_3
#
describe "W3C test" do
  context "project-expression" do
    before :all do
      @data = %q{
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .
@prefix ex:	<http://www.example.org/schema#>.
@prefix in:	<http://www.example.org/instance#>.

in:a ex:p 1 .
in:a ex:p ex:a .



}
      @query = %q{
prefix ex:	<http://www.example.org/schema#>
prefix in:	<http://www.example.org/instance#>

select ?x ?l (datatype(?l) as ?dt) where {
  ?x ex:p ?l
}
}
    end

    example "Expression may return no value" do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'project-expression-projexp05'
      expected = [
          { 
              :dt => RDF::URI('http://www.w3.org/2001/XMLSchema#integer'),
              :l => RDF::Literal.new('1' , :datatype => RDF::URI('http://www.w3.org/2001/XMLSchema#integer')),
              :x => RDF::URI('http://www.example.org/instance#a'),
          },
          { 
              :l => RDF::URI('http://www.example.org/schema#a'),
              :x => RDF::URI('http://www.example.org/instance#a'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
