# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# Cast to xsd:integer
# 
# /Users/ben/repos/datagraph/tests/tests/data-r2/cast/cast-int.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#cast-int
#
# This test is approved: 
# http://lists.w3.org/Archives/Public/public-rdf-dawg/2007JulSep/att-0087/14-dawg-minutes.html
#
describe "W3C test" do
  context "cast" do
    before :all do
      @data = %q{
@prefix : <http://example.org/> .

:iri :p :z .
:str :p "string" .
:fltdbl :p "-10.2E3" .
:decimal :p "+33.3300" .
:int :p "13" .
:dT :p "2002-10-10T17:00:00Z" .
:bool :p "true" .

}
      @query = %q{
(select (?s)
  (project (?s)
    (filter (= (datatype (<http://www.w3.org/2001/XMLSchema#integer> ?v)) <http://www.w3.org/2001/XMLSchema#integer>)
      (bgp (triple ?s <http://example.org/p> ?v)))))

}
    end

    example "Cast to xsd:integer" do
    
      graphs = {}
      graphs[:default] = { :data => @data, :format => :ttl}


      repository = 'cast-cast-int'
      results = [
          { 
              :s => RDF::URI('http://example.org/int'),
          },
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ results
    end
  end
end
